CREATE DATABASE IF NOT EXISTS chat;
USE chat;
CREATE TABLE Users(
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `login` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(200) NOT NULL
);

CREATE TABLE Messages(
	`ìd` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `content` VARCHAR(500) NOT NULL,
    `user_id` INT NOT NULL,
    `creation_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id)
)